"""Quality permission constants per ERD_09."""

QM_PERMISSIONS: list[tuple[str, str, str, str]] = [
    ("quality.inspection_plan:read", "quality.inspection_plan", "read", "quality"),
    ("quality.inspection_plan:create", "quality.inspection_plan", "create", "quality"),
    ("quality.inspection_plan:update", "quality.inspection_plan", "update", "quality"),
    ("quality.sampling_plan:read", "quality.sampling_plan", "read", "quality"),
    ("quality.sampling_plan:create", "quality.sampling_plan", "create", "quality"),
    ("quality.sampling_plan:update", "quality.sampling_plan", "update", "quality"),
    ("quality.characteristic:read", "quality.characteristic", "read", "quality"),
    ("quality.characteristic:create", "quality.characteristic", "create", "quality"),
    ("quality.characteristic:update", "quality.characteristic", "update", "quality"),
    ("quality.incoming_inspection:read", "quality.incoming_inspection", "read", "quality"),
    ("quality.incoming_inspection:create", "quality.incoming_inspection", "create", "quality"),
    ("quality.incoming_inspection:update", "quality.incoming_inspection", "update", "quality"),
    ("quality.incoming_inspection:complete", "quality.incoming_inspection", "complete", "quality"),
    ("quality.incoming_inspection:approve", "quality.incoming_inspection", "approve", "quality"),
    ("quality.inprocess_inspection:read", "quality.inprocess_inspection", "read", "quality"),
    ("quality.inprocess_inspection:create", "quality.inprocess_inspection", "create", "quality"),
    ("quality.inprocess_inspection:complete", "quality.inprocess_inspection", "complete", "quality"),
    ("quality.final_inspection:read", "quality.final_inspection", "read", "quality"),
    ("quality.final_inspection:create", "quality.final_inspection", "create", "quality"),
    ("quality.final_inspection:submit", "quality.final_inspection", "submit", "quality"),
    ("quality.final_inspection:approve", "quality.final_inspection", "approve", "quality"),
    ("quality.final_inspection:complete", "quality.final_inspection", "complete", "quality"),
    ("quality.defect:read", "quality.defect", "read", "quality"),
    ("quality.defect:create", "quality.defect", "create", "quality"),
    ("quality.defect:update", "quality.defect", "update", "quality"),
    ("quality.defect_type:read", "quality.defect_type", "read", "quality"),
    ("quality.defect_type:create", "quality.defect_type", "create", "quality"),
    ("quality.defect_type:update", "quality.defect_type", "update", "quality"),
    ("quality.ncr:read", "quality.ncr", "read", "quality"),
    ("quality.ncr:create", "quality.ncr", "create", "quality"),
    ("quality.ncr:submit", "quality.ncr", "submit", "quality"),
    ("quality.ncr:approve", "quality.ncr", "approve", "quality"),
    ("quality.ncr:close", "quality.ncr", "close", "quality"),
    ("quality.capa:read", "quality.capa", "read", "quality"),
    ("quality.capa:create", "quality.capa", "create", "quality"),
    ("quality.capa:submit", "quality.capa", "submit", "quality"),
    ("quality.capa:approve", "quality.capa", "approve", "quality"),
    ("quality.capa:verify", "quality.capa", "verify", "quality"),
    ("quality.capa:close", "quality.capa", "close", "quality"),
    ("quality.supplier_quality:read", "quality.supplier_quality", "read", "quality"),
    ("quality.supplier_quality:publish", "quality.supplier_quality", "publish", "quality"),
    ("quality.customer_complaint:read", "quality.customer_complaint", "read", "quality"),
    ("quality.customer_complaint:create", "quality.customer_complaint", "create", "quality"),
    ("quality.customer_complaint:update", "quality.customer_complaint", "update", "quality"),
    ("quality.customer_complaint:close", "quality.customer_complaint", "close", "quality"),
    ("quality.audit:read", "quality.audit", "read", "quality"),
    ("quality.audit:create", "quality.audit", "create", "quality"),
    ("quality.audit:update", "quality.audit", "update", "quality"),
    ("quality.audit:close", "quality.audit", "close", "quality"),
    ("quality.score:read", "quality.score", "read", "quality"),
    ("quality.score:publish", "quality.score", "publish", "quality"),
    ("quality.report:read", "quality.report", "read", "quality"),
    ("quality.report:export", "quality.report", "export", "quality"),
    ("quality.pfmea:read", "quality.pfmea", "read", "quality"),
    ("quality.pfmea:create", "quality.pfmea", "create", "quality"),
    ("quality.pfmea:update", "quality.pfmea", "update", "quality"),
    ("quality.ppap:read", "quality.ppap", "read", "quality"),
    ("quality.ppap:create", "quality.ppap", "create", "quality"),
    ("quality.ppap:update", "quality.ppap", "update", "quality"),
    ("quality.ppap:submit", "quality.ppap", "submit", "quality"),
    ("quality.ppap:approve", "quality.ppap", "approve", "quality"),
    ("quality.spc_reading:read", "quality.spc_reading", "read", "quality"),
    ("quality.spc_reading:create", "quality.spc_reading", "create", "quality"),
    ("quality.scar:read", "quality.scar", "read", "quality"),
    ("quality.scar:create", "quality.scar", "create", "quality"),
    ("quality.scar:update", "quality.scar", "update", "quality"),
    ("quality.scar:issue", "quality.scar", "issue", "quality"),
    ("quality.scar:verify", "quality.scar", "verify", "quality"),
    ("quality.scar:close", "quality.scar", "close", "quality"),
    ("quality.vin_trace:read", "quality.vin_trace", "read", "quality"),
    ("quality.vin_trace:create", "quality.vin_trace", "create", "quality"),
    ("quality.vin_trace:update", "quality.vin_trace", "update", "quality"),
    ("quality.warranty_claim:read", "quality.warranty_claim", "read", "quality"),
    ("quality.warranty_claim:create", "quality.warranty_claim", "create", "quality"),
    ("quality.warranty_claim:update", "quality.warranty_claim", "update", "quality"),
    ("quality.warranty_claim:close", "quality.warranty_claim", "close", "quality"),
    ("quality.recall:read", "quality.recall", "read", "quality"),
    ("quality.recall:create", "quality.recall", "create", "quality"),
    ("quality.recall:update", "quality.recall", "update", "quality"),
    ("quality.recall:close", "quality.recall", "close", "quality"),
]

QM_AUTO_PERMISSIONS = [
    "quality.pfmea:read",
    "quality.pfmea:create",
    "quality.pfmea:update",
    "quality.ppap:read",
    "quality.ppap:create",
    "quality.ppap:update",
    "quality.ppap:submit",
    "quality.ppap:approve",
]

QM_SPC_PERMISSIONS = [
    "quality.spc_reading:read",
    "quality.spc_reading:create",
]

QM_SCAR_PERMISSIONS = [
    "quality.scar:read",
    "quality.scar:create",
    "quality.scar:update",
    "quality.scar:issue",
    "quality.scar:verify",
    "quality.scar:close",
]

QM_VIN_PERMISSIONS = [
    "quality.vin_trace:read",
    "quality.vin_trace:create",
    "quality.vin_trace:update",
]

QM_WARRANTY_PERMISSIONS = [
    "quality.warranty_claim:read",
    "quality.warranty_claim:create",
    "quality.warranty_claim:update",
    "quality.warranty_claim:close",
]

QM_RECALL_PERMISSIONS = [
    "quality.recall:read",
    "quality.recall:create",
    "quality.recall:update",
    "quality.recall:close",
]

QM_PHASE16_PERMISSIONS = sorted(
    set(
        QM_AUTO_PERMISSIONS
        + QM_SPC_PERMISSIONS
        + QM_SCAR_PERMISSIONS
        + QM_VIN_PERMISSIONS
        + QM_WARRANTY_PERMISSIONS
        + QM_RECALL_PERMISSIONS
    )
)

QUALITY_INSPECTOR_PERMISSIONS = [
    "quality.inspection_plan:read",
    "quality.sampling_plan:read",
    "quality.characteristic:read",
    "quality.incoming_inspection:read",
    "quality.incoming_inspection:create",
    "quality.incoming_inspection:update",
    "quality.incoming_inspection:complete",
    "quality.inprocess_inspection:read",
    "quality.inprocess_inspection:create",
    "quality.inprocess_inspection:complete",
    "quality.final_inspection:read",
    "quality.final_inspection:create",
    "quality.final_inspection:submit",
    "quality.defect:read",
    "quality.defect:create",
    "quality.defect_type:read",
    "quality.ncr:read",
    "quality.ncr:create",
    "quality.ncr:submit",
    "quality.customer_complaint:read",
    "quality.customer_complaint:create",
    "quality.audit:read",
    "quality.score:read",
    "quality.report:read",
    "quality.pfmea:read",
    "quality.ppap:read",
    "quality.spc_reading:read",
    "quality.spc_reading:create",
    "quality.scar:read",
    "quality.scar:create",
    "quality.scar:update",
    "quality.vin_trace:read",
    "quality.vin_trace:create",
    "quality.vin_trace:update",
    "quality.warranty_claim:read",
    "quality.warranty_claim:create",
    "quality.warranty_claim:update",
    "quality.recall:read",
    "quality.recall:create",
    "quality.recall:update",
]

QUALITY_ENGINEER_PERMISSIONS = QUALITY_INSPECTOR_PERMISSIONS + [
    "quality.inspection_plan:create",
    "quality.inspection_plan:update",
    "quality.sampling_plan:create",
    "quality.sampling_plan:update",
    "quality.characteristic:create",
    "quality.characteristic:update",
    "quality.defect_type:create",
    "quality.defect_type:update",
    "quality.defect:update",
    "quality.capa:read",
    "quality.capa:create",
    "quality.capa:submit",
    "quality.capa:verify",
    "quality.supplier_quality:read",
    "quality.customer_complaint:update",
    "quality.pfmea:create",
    "quality.pfmea:update",
    "quality.ppap:create",
    "quality.ppap:update",
    "quality.ppap:submit",
    "quality.scar:issue",
]

QUALITY_AUDITOR_PERMISSIONS = [
    "quality.inspection_plan:read",
    "quality.sampling_plan:read",
    "quality.characteristic:read",
    "quality.incoming_inspection:read",
    "quality.inprocess_inspection:read",
    "quality.final_inspection:read",
    "quality.defect:read",
    "quality.defect_type:read",
    "quality.ncr:read",
    "quality.capa:read",
    "quality.supplier_quality:read",
    "quality.customer_complaint:read",
    "quality.audit:read",
    "quality.audit:create",
    "quality.audit:update",
    "quality.audit:close",
    "quality.score:read",
    "quality.report:read",
    "quality.report:export",
    "quality.pfmea:read",
    "quality.ppap:read",
    "quality.spc_reading:read",
    "quality.scar:read",
    "quality.vin_trace:read",
    "quality.warranty_claim:read",
    "quality.recall:read",
]

QUALITY_MANAGER_PERMISSIONS = sorted(
    set(
        QUALITY_ENGINEER_PERMISSIONS
        + QUALITY_AUDITOR_PERMISSIONS
        + [
            "quality.incoming_inspection:approve",
            "quality.final_inspection:approve",
            "quality.final_inspection:complete",
            "quality.ncr:approve",
            "quality.ncr:close",
            "quality.capa:approve",
            "quality.capa:close",
            "quality.supplier_quality:publish",
            "quality.customer_complaint:close",
            "quality.score:publish",
            "quality.report:export",
            "quality.ppap:approve",
            "quality.scar:verify",
            "quality.scar:close",
            "quality.warranty_claim:close",
            "quality.recall:close",
        ]
    )
)
