"""Quality permission constants per ERD_09."""

QM_PERMISSIONS: list[tuple[str, str, str, str]] = [
    ("quality.inspection_plan:read", "quality.inspection_plan", "read", "quality"),
    ("quality.inspection_plan:create", "quality.inspection_plan", "create", "quality"),
    ("quality.inspection_plan:update", "quality.inspection_plan", "update", "quality"),
    ("quality.sampling_plan:read", "quality.sampling_plan", "read", "quality"),
    ("quality.sampling_plan:create", "quality.sampling_plan", "create", "quality"),
    ("quality.sampling_plan:update", "quality.sampling_plan", "update", "quality"),
    ("quality.characteristic:read", "quality.characteristic", "read", "quality"),
    ("quality.characteristic:create", "quality.characteristic", "create", "quality"),
    ("quality.characteristic:update", "quality.characteristic", "update", "quality"),
    ("quality.incoming_inspection:read", "quality.incoming_inspection", "read", "quality"),
    ("quality.incoming_inspection:create", "quality.incoming_inspection", "create", "quality"),
    ("quality.incoming_inspection:update", "quality.incoming_inspection", "update", "quality"),
    ("quality.incoming_inspection:complete", "quality.incoming_inspection", "complete", "quality"),
    ("quality.incoming_inspection:approve", "quality.incoming_inspection", "approve", "quality"),
    ("quality.inprocess_inspection:read", "quality.inprocess_inspection", "read", "quality"),
    ("quality.inprocess_inspection:create", "quality.inprocess_inspection", "create", "quality"),
    ("quality.inprocess_inspection:complete", "quality.inprocess_inspection", "complete", "quality"),
    ("quality.final_inspection:read", "quality.final_inspection", "read", "quality"),
    ("quality.final_inspection:create", "quality.final_inspection", "create", "quality"),
    ("quality.final_inspection:submit", "quality.final_inspection", "submit", "quality"),
    ("quality.final_inspection:approve", "quality.final_inspection", "approve", "quality"),
    ("quality.final_inspection:complete", "quality.final_inspection", "complete", "quality"),
    ("quality.defect:read", "quality.defect", "read", "quality"),
    ("quality.defect:create", "quality.defect", "create", "quality"),
    ("quality.defect:update", "quality.defect", "update", "quality"),
    ("quality.defect_type:read", "quality.defect_type", "read", "quality"),
    ("quality.defect_type:create", "quality.defect_type", "create", "quality"),
    ("quality.defect_type:update", "quality.defect_type", "update", "quality"),
    ("quality.ncr:read", "quality.ncr", "read", "quality"),
    ("quality.ncr:create", "quality.ncr", "create", "quality"),
    ("quality.ncr:submit", "quality.ncr", "submit", "quality"),
    ("quality.ncr:approve", "quality.ncr", "approve", "quality"),
    ("quality.ncr:close", "quality.ncr", "close", "quality"),
    ("quality.capa:read", "quality.capa", "read", "quality"),
    ("quality.capa:create", "quality.capa", "create", "quality"),
    ("quality.capa:submit", "quality.capa", "submit", "quality"),
    ("quality.capa:approve", "quality.capa", "approve", "quality"),
    ("quality.capa:verify", "quality.capa", "verify", "quality"),
    ("quality.capa:close", "quality.capa", "close", "quality"),
    ("quality.supplier_quality:read", "quality.supplier_quality", "read", "quality"),
    ("quality.supplier_quality:publish", "quality.supplier_quality", "publish", "quality"),
    ("quality.customer_complaint:read", "quality.customer_complaint", "read", "quality"),
    ("quality.customer_complaint:create", "quality.customer_complaint", "create", "quality"),
    ("quality.customer_complaint:update", "quality.customer_complaint", "update", "quality"),
    ("quality.customer_complaint:close", "quality.customer_complaint", "close", "quality"),
    ("quality.audit:read", "quality.audit", "read", "quality"),
    ("quality.audit:create", "quality.audit", "create", "quality"),
    ("quality.audit:update", "quality.audit", "update", "quality"),
    ("quality.audit:close", "quality.audit", "close", "quality"),
    ("quality.score:read", "quality.score", "read", "quality"),
    ("quality.score:publish", "quality.score", "publish", "quality"),
    ("quality.report:read", "quality.report", "read", "quality"),
    ("quality.report:export", "quality.report", "export", "quality"),
]

QUALITY_INSPECTOR_PERMISSIONS = [
    "quality.inspection_plan:read",
    "quality.sampling_plan:read",
    "quality.characteristic:read",
    "quality.incoming_inspection:read",
    "quality.incoming_inspection:create",
    "quality.incoming_inspection:update",
    "quality.incoming_inspection:complete",
    "quality.inprocess_inspection:read",
    "quality.inprocess_inspection:create",
    "quality.inprocess_inspection:complete",
    "quality.final_inspection:read",
    "quality.final_inspection:create",
    "quality.final_inspection:submit",
    "quality.defect:read",
    "quality.defect:create",
    "quality.defect_type:read",
    "quality.ncr:read",
    "quality.ncr:create",
    "quality.ncr:submit",
    "quality.customer_complaint:read",
    "quality.customer_complaint:create",
    "quality.audit:read",
    "quality.score:read",
    "quality.report:read",
]

QUALITY_ENGINEER_PERMISSIONS = QUALITY_INSPECTOR_PERMISSIONS + [
    "quality.inspection_plan:create",
    "quality.inspection_plan:update",
    "quality.sampling_plan:create",
    "quality.sampling_plan:update",
    "quality.characteristic:create",
    "quality.characteristic:update",
    "quality.defect_type:create",
    "quality.defect_type:update",
    "quality.defect:update",
    "quality.capa:read",
    "quality.capa:create",
    "quality.capa:submit",
    "quality.capa:verify",
    "quality.supplier_quality:read",
    "quality.customer_complaint:update",
]

QUALITY_AUDITOR_PERMISSIONS = [
    "quality.inspection_plan:read",
    "quality.sampling_plan:read",
    "quality.characteristic:read",
    "quality.incoming_inspection:read",
    "quality.inprocess_inspection:read",
    "quality.final_inspection:read",
    "quality.defect:read",
    "quality.defect_type:read",
    "quality.ncr:read",
    "quality.capa:read",
    "quality.supplier_quality:read",
    "quality.customer_complaint:read",
    "quality.audit:read",
    "quality.audit:create",
    "quality.audit:update",
    "quality.audit:close",
    "quality.score:read",
    "quality.report:read",
    "quality.report:export",
]

QUALITY_MANAGER_PERMISSIONS = sorted(
    set(
        QUALITY_ENGINEER_PERMISSIONS
        + QUALITY_AUDITOR_PERMISSIONS
        + [
            "quality.incoming_inspection:approve",
            "quality.final_inspection:approve",
            "quality.final_inspection:complete",
            "quality.ncr:approve",
            "quality.ncr:close",
            "quality.capa:approve",
            "quality.capa:close",
            "quality.supplier_quality:publish",
            "quality.customer_complaint:close",
            "quality.score:publish",
            "quality.report:export",
        ]
    )
)
