"""CRM permission constants per ERD_10."""

CRM_PERMISSIONS: list[tuple[str, str, str, str]] = [
    ("crm.lead_source:read", "crm.lead_source", "read", "crm"),
    ("crm.lead_source:create", "crm.lead_source", "create", "crm"),
    ("crm.lead_source:update", "crm.lead_source", "update", "crm"),
    ("crm.pipeline:read", "crm.pipeline", "read", "crm"),
    ("crm.pipeline:create", "crm.pipeline", "create", "crm"),
    ("crm.pipeline:update", "crm.pipeline", "update", "crm"),
    ("crm.campaign:read", "crm.campaign", "read", "crm"),
    ("crm.campaign:create", "crm.campaign", "create", "crm"),
    ("crm.campaign:update", "crm.campaign", "update", "crm"),
    ("crm.lead:read", "crm.lead", "read", "crm"),
    ("crm.lead:create", "crm.lead", "create", "crm"),
    ("crm.lead:update", "crm.lead", "update", "crm"),
    ("crm.lead:assign", "crm.lead", "assign", "crm"),
    ("crm.lead:convert", "crm.lead", "convert", "crm"),
    ("crm.opportunity:read", "crm.opportunity", "read", "crm"),
    ("crm.opportunity:create", "crm.opportunity", "create", "crm"),
    ("crm.opportunity:update", "crm.opportunity", "update", "crm"),
    ("crm.opportunity:close", "crm.opportunity", "close", "crm"),
    ("crm.task:read", "crm.task", "read", "crm"),
    ("crm.task:create", "crm.task", "create", "crm"),
    ("crm.task:update", "crm.task", "update", "crm"),
    ("crm.task:complete", "crm.task", "complete", "crm"),
    ("crm.followup:read", "crm.followup", "read", "crm"),
    ("crm.followup:create", "crm.followup", "create", "crm"),
    ("crm.followup:update", "crm.followup", "update", "crm"),
    ("crm.followup:complete", "crm.followup", "complete", "crm"),
    ("crm.meeting:read", "crm.meeting", "read", "crm"),
    ("crm.meeting:create", "crm.meeting", "create", "crm"),
    ("crm.meeting:update", "crm.meeting", "update", "crm"),
    ("crm.meeting:complete", "crm.meeting", "complete", "crm"),
    ("crm.interaction:read", "crm.interaction", "read", "crm"),
    ("crm.interaction:create", "crm.interaction", "create", "crm"),
    ("crm.call_log:read", "crm.call_log", "read", "crm"),
    ("crm.call_log:create", "crm.call_log", "create", "crm"),
    ("crm.email_log:read", "crm.email_log", "read", "crm"),
    ("crm.email_log:create", "crm.email_log", "create", "crm"),
    ("crm.visit_log:read", "crm.visit_log", "read", "crm"),
    ("crm.visit_log:create", "crm.visit_log", "create", "crm"),
    ("crm.feedback:read", "crm.feedback", "read", "crm"),
    ("crm.feedback:create", "crm.feedback", "create", "crm"),
    ("crm.feedback:close", "crm.feedback", "close", "crm"),
    ("crm.satisfaction:read", "crm.satisfaction", "read", "crm"),
    ("crm.satisfaction:create", "crm.satisfaction", "create", "crm"),
    ("crm.satisfaction:publish", "crm.satisfaction", "publish", "crm"),
    ("crm.report:read", "crm.report", "read", "crm"),
    ("crm.report:export", "crm.report", "export", "crm"),
]

CRM_SALES_REP_PERMISSIONS = [
    "crm.lead_source:read",
    "crm.pipeline:read",
    "crm.campaign:read",
    "crm.lead:read",
    "crm.lead:create",
    "crm.lead:update",
    "crm.lead:assign",
    "crm.opportunity:read",
    "crm.opportunity:create",
    "crm.opportunity:update",
    "crm.task:read",
    "crm.task:create",
    "crm.task:update",
    "crm.task:complete",
    "crm.followup:read",
    "crm.followup:create",
    "crm.followup:update",
    "crm.followup:complete",
    "crm.meeting:read",
    "crm.meeting:create",
    "crm.meeting:update",
    "crm.meeting:complete",
    "crm.interaction:read",
    "crm.interaction:create",
    "crm.call_log:read",
    "crm.call_log:create",
    "crm.email_log:read",
    "crm.email_log:create",
    "crm.visit_log:read",
    "crm.visit_log:create",
    "crm.feedback:read",
    "crm.feedback:create",
    "crm.satisfaction:read",
    "crm.report:read",
]

CRM_SALES_MANAGER_PERMISSIONS = list(
    dict.fromkeys(
        CRM_SALES_REP_PERMISSIONS
        + [
            "crm.lead:convert",
            "crm.opportunity:close",
            "crm.campaign:create",
            "crm.campaign:update",
            "crm.pipeline:create",
            "crm.pipeline:update",
            "crm.lead_source:create",
            "crm.lead_source:update",
            "crm.feedback:close",
            "crm.satisfaction:create",
            "crm.satisfaction:publish",
            "crm.report:export",
        ]
    )
)

CRM_MARKETING_PERMISSIONS = [
    "crm.lead_source:read",
    "crm.lead_source:create",
    "crm.lead_source:update",
    "crm.campaign:read",
    "crm.campaign:create",
    "crm.campaign:update",
    "crm.pipeline:read",
    "crm.lead:read",
    "crm.lead:create",
    "crm.interaction:read",
    "crm.interaction:create",
    "crm.feedback:read",
    "crm.satisfaction:read",
    "crm.report:read",
    "crm.report:export",
]

CRM_ADMIN_PERMISSIONS = [p[0] for p in CRM_PERMISSIONS]
