"""Workflow code map for asset governance."""

from modules.asset.domain.workflow_codes import (
    ENTITY_AST_ASSET,
    ENTITY_AST_ASSIGNMENT,
    ENTITY_AST_DISPOSAL,
    ENTITY_AST_MAINTENANCE,
    ENTITY_AST_REVALUATION,
    ENTITY_AST_TRANSFER,
    WORKFLOW_CODES,
)


def test_workflow_codes_map_to_seeded_definitions() -> None:
    assert WORKFLOW_CODES[ENTITY_AST_ASSET] == "AST_ASSET_APPROVAL"
    assert WORKFLOW_CODES[ENTITY_AST_ASSIGNMENT] == "AST_ASSIGNMENT_APPROVAL"
    assert WORKFLOW_CODES[ENTITY_AST_TRANSFER] == "AST_TRANSFER_APPROVAL"
    assert WORKFLOW_CODES[ENTITY_AST_MAINTENANCE] == "AST_MAINTENANCE_APPROVAL"
    assert WORKFLOW_CODES[ENTITY_AST_DISPOSAL] == "AST_DISPOSAL_APPROVAL"
    assert WORKFLOW_CODES[ENTITY_AST_REVALUATION] == "AST_REVALUATION_APPROVAL"
    assert len(WORKFLOW_CODES) == 6
