"""CRM custom report module / column catalog."""

from __future__ import annotations

from core.exceptions import ValidationException


def _col(key: str, label: str) -> dict[str, str]:
    return {"key": key, "label": label}


REPORT_MODULES: list[dict[str, str]] = [
    {"key": "companies", "label": "Companies"},
    {"key": "leads", "label": "Leads"},
    {"key": "opportunities", "label": "Opportunities"},
    {"key": "oem_quotes", "label": "OEM Quotes"},
    {"key": "quotes", "label": "Quotes"},
    {"key": "purchase_orders", "label": "Purchase Orders"},
    {"key": "ovf", "label": "OVF"},
    {"key": "contacts", "label": "Contacts"},
    {"key": "products", "label": "Products"},
    {"key": "meetings", "label": "Meetings"},
    {"key": "customer_followups", "label": "Customer Follow-ups"},
    {"key": "kyc", "label": "KYC"},
    {"key": "oem", "label": "OEM"},
    {"key": "distributors", "label": "Distributors"},
    {"key": "boq", "label": "BOQ"},
    {"key": "sow", "label": "SOW"},
    {"key": "entities", "label": "Entities"},
    {"key": "end_customers", "label": "End Customers"},
]

# Lead-sourced keys available on opportunity reports (joined via lead_id).
# Kept for documentation / callers; enrichment uses full lead row fallback.
OPPORTUNITY_LEAD_FIELD_KEYS: frozenset[str] = frozenset(
    {
        "lead_code",
        "salutation",
        "first_name",
        "last_name",
        "designation",
        "email",
        "mobile",
        "company_name",
        "territory",
        "industry",
        "region",
        "budget_amount",
        "expected_amount",
        "committed_amount",
        "expected_closure_date",
        "requirement_type",
        "purchase_model",
        "dr_number",
        "new_dr_number",
        "deal_type",
        "engagement_score",
        "sub_product_category",
        "sub_product",
        "sub_product_other",
        "street",
        "city",
        "state",
        "zip",
        "country",
        "oem_name",
        "oem_contact_person",
        "oem_contact_number",
        "oem_contact_email",
        "distributor_name",
        "distributor_contact",
        "distributor_contact_person",
        "distributor_contact_email",
        "distributor_department",
        "end_customer_name",
        "end_customer_location",
        "entity_name",
        "entity_email",
        "entity_address",
        "entity_gst",
        "entity_contact",
        "portal_link",
        "convert_remark",
        "presales_owner_id",
    }
)

COLUMNS: dict[str, list[dict[str, str]]] = {
    "companies": [
        _col("account_number", "Account Number"),
        _col("customer_name", "Customer Name"),
        _col("account_type", "Account Type"),
        _col("industry", "Industry"),
        _col("other_industries", "Other Industries"),
        _col("source", "Source"),
        _col("rating", "Rating"),
        _col("portal_id", "Portal ID"),
        _col("first_name", "First Name"),
        _col("last_name", "Last Name"),
        _col("customer_email", "Email"),
        _col("phone", "Phone"),
        _col("website", "Website"),
        _col("role", "Role"),
        _col("customer_id_ext", "External Customer ID"),
        _col("billing_street", "Billing Street"),
        _col("billing_city", "Billing City"),
        _col("billing_state", "Billing State"),
        _col("billing_code", "Billing Code"),
        _col("billing_country", "Billing Country"),
        _col("shipping_street", "Shipping Street"),
        _col("shipping_city", "Shipping City"),
        _col("shipping_state", "Shipping State"),
        _col("shipping_code", "Shipping Code"),
        _col("shipping_country", "Shipping Country"),
        _col("description", "Description"),
        _col("account_owner_id", "Account Owner"),
        _col("master_customer_id", "Master Customer"),
        _col("status", "Status"),
        _col("locked", "Locked"),
        _col("created_at", "Created At"),
        _col("created_by", "Created By"),
    ],
    "leads": [
        _col("lead_code", "Lead Code"),
        _col("document_date", "Document Date"),
        _col("salutation", "Salutation"),
        _col("first_name", "First Name"),
        _col("last_name", "Last Name"),
        _col("designation", "Designation"),
        _col("company_name", "Company Name"),
        _col("company_account_name", "Company Account"),
        _col("email", "Email"),
        _col("mobile", "Mobile"),
        _col("status", "Status"),
        _col("blueprint_state", "Blueprint State"),
        _col("locked", "Locked"),
        _col("territory", "Territory"),
        _col("industry", "Industry"),
        _col("region", "Region"),
        _col("street", "Street"),
        _col("city", "City"),
        _col("state", "State"),
        _col("zip", "Zip"),
        _col("country", "Country"),
        _col("budget_amount", "Budget Amount"),
        _col("expected_amount", "Expected Amount"),
        _col("committed_amount", "Committed Amount"),
        _col("expected_closure_date", "Expected Closure Date"),
        _col("project_title", "Project Title"),
        _col("product_type", "Product Type"),
        _col("sub_product_category", "Sub Product Category"),
        _col("sub_product", "Sub Product"),
        _col("sub_product_other", "Sub Product Other"),
        _col("requirement_type", "Requirement Type"),
        _col("purchase_model", "Purchase Model"),
        _col("dr_number", "DR Number"),
        _col("new_dr_number", "New DR Number"),
        _col("deal_type", "Sourcing Channel"),
        _col("engagement_score", "Engagement Score"),
        _col("portal_link", "Portal Link"),
        _col("oem_name", "OEM Name"),
        _col("oem_contact_person", "OEM Contact Person"),
        _col("oem_contact_number", "OEM Contact Number"),
        _col("oem_contact_email", "OEM Contact Email"),
        _col("distributor_name", "Distributor Name"),
        _col("distributor_contact", "Distributor Contact"),
        _col("distributor_contact_person", "Distributor Contact Person"),
        _col("distributor_contact_email", "Distributor Contact Email"),
        _col("distributor_department", "Distributor Department"),
        _col("end_customer_name", "End Customer"),
        _col("end_customer_location", "End Customer Location"),
        _col("entity_name", "Entity Name"),
        _col("entity_email", "Entity Email"),
        _col("entity_address", "Entity Address"),
        _col("entity_gst", "Entity GST"),
        _col("entity_contact", "Entity Contact"),
        _col("lead_source_id", "Lead Source"),
        _col("owner_employee_id", "Owner Employee"),
        _col("presales_owner_id", "Presales Owner"),
        _col("assign_to_id", "Assign To"),
        _col("assigned_date", "Assigned Date"),
        _col("company_account_id", "Company Account ID"),
        _col("converted_opportunity_id", "Converted Opportunity"),
        _col("converted_at", "Converted At"),
        _col("lost_reason", "Lost Reason"),
        _col("convert_remark", "Convert Remark"),
        _col("notes", "Notes"),
        _col("qualification_score", "Qualification Score"),
        _col("has_authority", "Has Authority"),
        _col("need_text", "Need"),
        _col("timeline_text", "Timeline"),
        _col("created_at", "Created At"),
        _col("created_by", "Created By"),
    ],
    "opportunities": [
        _col("opportunity_code", "Opportunity Code"),
        _col("opportunity_name", "Opportunity Name"),
        _col("document_date", "Document Date"),
        _col("current_stage", "Current Stage"),
        _col("status", "Status"),
        _col("blueprint_state", "Blueprint State"),
        _col("locked", "Locked"),
        _col("expected_revenue", "Expected Revenue"),
        _col("probability_percent", "Probability %"),
        _col("expected_close_date", "Expected Close Date"),
        _col("forecast_amount", "Forecast Amount"),
        _col("project_title", "Project Title"),
        _col("company_account_name", "Company Account"),
        _col("lead_code", "Lead Code"),
        _col("salutation", "Salutation"),
        _col("first_name", "First Name"),
        _col("last_name", "Last Name"),
        _col("designation", "Designation"),
        _col("email", "Email"),
        _col("mobile", "Mobile"),
        _col("company_name", "Company Name"),
        _col("territory", "Territory"),
        _col("industry", "Industry"),
        _col("region", "Region"),
        _col("street", "Street"),
        _col("city", "City"),
        _col("state", "State"),
        _col("zip", "Zip"),
        _col("country", "Country"),
        _col("budget_amount", "Budget Amount"),
        _col("expected_amount", "Lead Expected Amount"),
        _col("committed_amount", "Committed Amount"),
        _col("expected_closure_date", "Lead Expected Closure"),
        _col("product_type", "Product Type"),
        _col("sub_product_category", "Sub Product Category"),
        _col("sub_product", "Sub Product"),
        _col("sub_product_other", "Sub Product Other"),
        _col("requirement_type", "Requirement Type"),
        _col("purchase_model", "Purchase Model"),
        _col("dr_number", "DR Number"),
        _col("new_dr_number", "New DR Number"),
        _col("deal_type", "Sourcing Channel"),
        _col("engagement_score", "Engagement Score"),
        _col("oem_name", "OEM Name"),
        _col("oem_contact_person", "OEM Contact Person"),
        _col("oem_contact_number", "OEM Contact Number"),
        _col("oem_contact_email", "OEM Contact Email"),
        _col("distributor_name", "Distributor Name"),
        _col("distributor_contact", "Distributor Contact"),
        _col("distributor_contact_person", "Distributor Contact Person"),
        _col("distributor_contact_email", "Distributor Contact Email"),
        _col("distributor_department", "Distributor Department"),
        _col("end_customer_name", "End Customer"),
        _col("end_customer_location", "End Customer Location"),
        _col("entity_name", "Entity Name"),
        _col("entity_email", "Entity Email"),
        _col("entity_address", "Entity Address"),
        _col("entity_gst", "Entity GST"),
        _col("entity_contact", "Entity Contact"),
        _col("deal_reg_number", "Deal Reg Number"),
        _col("deal_won_amount", "Deal Won Amount"),
        _col("boq_attached", "BOQ Attached"),
        _col("boq_approved", "BOQ Approved"),
        _col("sow_attached", "SOW Attached"),
        _col("sow_approved", "SOW Approved"),
        _col("sow_skipped", "SOW Skipped"),
        _col("oem_quotation_received", "OEM Quotation Received"),
        _col("oem_quote_attached", "OEM Quote Attached"),
        _col("customer_po_attached", "Customer PO Attached"),
        _col("customer_po_approved", "Customer PO Approved"),
        _col("has_hardware", "Has Hardware"),
        _col("has_software", "Has Software"),
        _col("has_services", "Has Services"),
        _col("cloud_blueprint_variant", "Cloud Blueprint Variant"),
        _col("cloud_sub_product", "Cloud Sub Product"),
        _col("customer_mrr", "Customer MRR"),
        _col("customer_arr", "Customer ARR"),
        _col("customer_discount_percent", "Customer Discount %"),
        _col("distributor_discount_percent", "Distributor Discount %"),
        _col("profitability_percent", "Profitability %"),
        _col("assessment_type", "Assessment Type"),
        _col("migration_credit_phase1", "Migration Credit Phase 1"),
        _col("migration_credit_phase2", "Migration Credit Phase 2"),
        _col("migration_credit_phase3", "Migration Credit Phase 3"),
        _col("contract_attached", "Contract Attached"),
        _col("onboarding_done", "Onboarding Done"),
        _col("onboarding_date", "Onboarding Date"),
        _col("won_at", "Won At"),
        _col("lost_at", "Lost At"),
        _col("lost_reason", "Lost Reason"),
        _col("notes", "Notes"),
        _col("portal_link", "Portal Link"),
        _col("convert_remark", "Convert Remark"),
        _col("lead_id", "Lead ID"),
        _col("company_account_id", "Company Account ID"),
        _col("customer_id", "Customer ID"),
        _col("owner_employee_id", "Owner Employee"),
        _col("presales_owner_id", "Presales Owner"),
        _col("created_at", "Created At"),
        _col("created_by", "Created By"),
    ],
    "oem_quotes": [
        _col("file_name", "File Name"),
        _col("category", "Category"),
        _col("entity_type", "Entity Type"),
        _col("entity_id", "Entity ID"),
        _col("source", "Source"),
        _col("content_type", "Content Type"),
        _col("size", "Size"),
        _col("uploaded_by", "Uploaded By"),
        _col("created_at", "Created At"),
        _col("created_by", "Created By"),
    ],
    "quotes": [
        _col("quote_no", "Quote No"),
        _col("quote_revision", "Revision"),
        _col("subject", "Subject"),
        _col("project_title", "Project Title"),
        _col("account_name", "Account Name"),
        _col("quote_stage", "Quote Stage"),
        _col("approval_status", "Approval Status"),
        _col("locked", "Locked"),
        _col("valid_until", "Valid Until"),
        _col("owner_name", "Owner Name"),
        _col("service_type", "Service Type"),
        _col("grand_total", "Grand Total"),
        _col("freight", "Freight"),
        _col("avg_margin_pct", "Avg Margin %"),
        _col("total_margin_amount", "Total Margin"),
        _col("entity_name", "Entity Name"),
        _col("entity_email", "Entity Email"),
        _col("entity_address", "Entity Address"),
        _col("entity_gst", "Entity GST"),
        _col("entity_contact", "Entity Contact"),
        _col("amc_warranty", "AMC / Warranty"),
        _col("amc_start_date", "AMC Start Date"),
        _col("amc_end_date", "AMC End Date"),
        _col("billing_street", "Billing Street"),
        _col("billing_city", "Billing City"),
        _col("billing_state", "Billing State"),
        _col("billing_zip", "Billing Zip"),
        _col("billing_country", "Billing Country"),
        _col("shipping_street", "Shipping Street"),
        _col("shipping_city", "Shipping City"),
        _col("shipping_state", "Shipping State"),
        _col("shipping_zip", "Shipping Zip"),
        _col("shipping_country", "Shipping Country"),
        _col("vendor_quote_attached", "Vendor Quote Attached"),
        _col("terms", "Terms"),
        _col("description", "Description"),
        _col("reason_for_discount", "Reason for Discount"),
        _col("opportunity_id", "Opportunity ID"),
        _col("company_account_id", "Company Account ID"),
        _col("contact_id", "Contact ID"),
        _col("created_at", "Created At"),
        _col("created_by", "Created By"),
    ],
    "purchase_orders": [
        _col("file_name", "File Name"),
        _col("category", "Category"),
        _col("entity_type", "Entity Type"),
        _col("entity_id", "Entity ID"),
        _col("source", "Source"),
        _col("content_type", "Content Type"),
        _col("size", "Size"),
        _col("uploaded_by", "Uploaded By"),
        _col("created_at", "Created At"),
        _col("created_by", "Created By"),
    ],
    "ovf": [
        _col("ovf_no", "OVF No"),
        _col("po_number", "PO Number"),
        _col("po_date", "PO Date"),
        _col("delivery_period", "Delivery Period"),
        _col("customer_name", "Customer Name"),
        _col("account_name", "Account Name"),
        _col("quote_name", "Quote Name"),
        _col("owner_name", "Owner Name"),
        _col("approval_status", "Approval Status"),
        _col("blueprint_state", "Blueprint State"),
        _col("locked", "Locked"),
        _col("deal_won", "Deal Won"),
        _col("deal_won_amount", "Deal Won Amount"),
        _col("vendor_payment_days", "Vendor Payment Days"),
        _col("customer_payment_days", "Customer Payment Days"),
        _col("finance_cost_pct", "Finance Cost %"),
        _col("freight", "Freight"),
        _col("additional_charges", "Additional Charges"),
        _col("total_margin_pct", "Total Margin %"),
        _col("total_margin_amount", "Total Margin Amount"),
        _col("billing_address", "Billing Address"),
        _col("billing_state", "Billing State"),
        _col("billing_country", "Billing Country"),
        _col("billing_contact_person", "Billing Contact"),
        _col("shipping_address", "Shipping Address"),
        _col("shipping_state", "Shipping State"),
        _col("shipping_country", "Shipping Country"),
        _col("shipping_contact_person", "Shipping Contact"),
        _col("technology_segment", "Technology Segment"),
        _col("sub_technology_segment", "Sub Technology Segment"),
        _col("installation_details", "Installation Details"),
        _col("shared_to_scm", "Shared to SCM"),
        _col("shared_to_scm_at", "Shared to SCM At"),
        _col("scm_on_hold", "SCM On Hold"),
        _col("scm_on_hold_remark", "SCM Hold Remark"),
        _col("opportunity_id", "Opportunity ID"),
        _col("quote_id", "Quote ID"),
        _col("company_account_id", "Company Account ID"),
        _col("created_at", "Created At"),
        _col("created_by", "Created By"),
    ],
    "contacts": [
        _col("first_name", "First Name"),
        _col("last_name", "Last Name"),
        _col("email", "Email"),
        _col("phone", "Phone"),
        _col("mobile", "Mobile"),
        _col("title", "Title"),
        _col("is_primary", "Is Primary"),
        _col("company_account_id", "Company Account"),
        _col("owner_id", "Owner"),
        _col("status", "Status"),
        _col("created_at", "Created At"),
        _col("created_by", "Created By"),
    ],
    "products": [
        _col("product_code", "Product Code"),
        _col("product_name", "Product Name"),
        _col("product_type", "Product Type"),
        _col("hsn_sac", "HSN / SAC"),
        _col("unit_price", "Unit Price"),
        _col("status", "Status"),
        _col("created_at", "Created At"),
        _col("created_by", "Created By"),
    ],
    "meetings": [
        _col("meeting_code", "Meeting Code"),
        _col("title", "Title"),
        _col("meeting_date", "Meeting Date"),
        _col("end_date", "End Date"),
        _col("start_time", "Start Time"),
        _col("end_time", "End Time"),
        _col("all_day", "All Day"),
        _col("location", "Location"),
        _col("meeting_mode", "Meeting Mode"),
        _col("related_to", "Related To"),
        _col("lead_id", "Lead"),
        _col("opportunity_id", "Opportunity"),
        _col("company_account_id", "Company Account"),
        _col("organizer_employee_id", "Organizer"),
        _col("tagged_employee_id", "Tagged Employee"),
        _col("status", "Status"),
        _col("outcome", "Outcome"),
        _col("repeat_rule", "Repeat Rule"),
        _col("created_at", "Created At"),
        _col("created_by", "Created By"),
    ],
    "customer_followups": [
        _col("followup_code", "Follow-up Code"),
        _col("customer_name", "Customer Name"),
        _col("followup_at", "Follow-up At"),
        _col("followup_type", "Follow-up Type"),
        _col("status", "Status"),
        _col("outcome", "Outcome"),
        _col("notes", "Notes"),
        _col("owner_employee_id", "Owner Employee"),
        _col("lead_id", "Lead"),
        _col("opportunity_id", "Opportunity"),
        _col("created_at", "Created At"),
        _col("created_by", "Created By"),
    ],
    "kyc": [
        _col("kyc_code", "KYC Code"),
        _col("company_account_id", "Company Account"),
        _col("owner_employee_id", "Owner Employee"),
        _col("quote_id", "Quote"),
        _col("status", "Status"),
        _col("created_at", "Created At"),
        _col("created_by", "Created By"),
    ],
    "oem": [
        _col("oem_code", "OEM Code"),
        _col("oem_name", "OEM Name"),
        _col("contact_person", "Contact Person"),
        _col("contact_number", "Contact Number"),
        _col("contact_email", "Contact Email"),
        _col("status", "Status"),
        _col("created_at", "Created At"),
        _col("created_by", "Created By"),
    ],
    "distributors": [
        _col("distributor_name", "Distributor Name"),
        _col("distributor_contact", "Distributor Contact"),
        _col("distributor_contact_person", "Contact Person"),
        _col("distributor_contact_email", "Contact Email"),
        _col("distributor_department", "Department"),
        _col("lead_code", "Source Lead Code"),
        _col("company_name", "Company Name"),
        _col("created_by", "Created By"),
    ],
    "boq": [
        _col("file_name", "File Name"),
        _col("category", "Category"),
        _col("entity_type", "Entity Type"),
        _col("entity_id", "Entity ID"),
        _col("source", "Source"),
        _col("content_type", "Content Type"),
        _col("size", "Size"),
        _col("uploaded_by", "Uploaded By"),
        _col("created_at", "Created At"),
        _col("created_by", "Created By"),
    ],
    "sow": [
        _col("file_name", "File Name"),
        _col("category", "Category"),
        _col("entity_type", "Entity Type"),
        _col("entity_id", "Entity ID"),
        _col("source", "Source"),
        _col("content_type", "Content Type"),
        _col("size", "Size"),
        _col("uploaded_by", "Uploaded By"),
        _col("created_at", "Created At"),
        _col("created_by", "Created By"),
    ],
    "entities": [
        _col("entity_code", "Entity Code"),
        _col("entity_name", "Entity Name"),
        _col("entity_email", "Entity Email"),
        _col("entity_contact", "Entity Contact"),
        _col("entity_gst", "Entity GST"),
        _col("entity_address", "Entity Address"),
        _col("status", "Status"),
        _col("created_at", "Created At"),
        _col("created_by", "Created By"),
    ],
    "end_customers": [
        _col("end_customer_name", "End Customer Name"),
        _col("end_customer_location", "Location"),
        _col("lead_code", "Source Lead Code"),
        _col("company_name", "Company Name"),
        _col("oem_name", "OEM Name"),
        _col("distributor_name", "Distributor Name"),
        _col("created_by", "Created By"),
    ],
}

_MODULE_LABELS = {m["key"]: m["label"] for m in REPORT_MODULES}


def list_modules() -> list[dict[str, str]]:
    return list(REPORT_MODULES)


def list_columns(module_key: str) -> list[dict[str, str]]:
    cols = COLUMNS.get(module_key)
    if cols is None:
        raise ValidationException(f"Unknown report module: {module_key}")
    return list(cols)


def get_module_label(module_key: str) -> str:
    label = _MODULE_LABELS.get(module_key)
    if label is None:
        raise ValidationException(f"Unknown report module: {module_key}")
    return label


def validate_columns(module_key: str, column_keys: list[str]) -> list[str]:
    cols = COLUMNS.get(module_key)
    if cols is None:
        raise ValidationException(f"Unknown report module: {module_key}")
    allowed = {c["key"] for c in cols}
    valid = [k for k in column_keys if k in allowed]
    if not valid:
        raise ValidationException("No valid columns selected for this module")
    return valid
