"""Master Data permission constants."""

MASTER_PERMISSIONS: list[tuple[str, str, str, str]] = [
    ("master.employee:read", "master.employee", "read", "master_data"),
    ("master.employee:create", "master.employee", "create", "master_data"),
    ("master.employee:update", "master.employee", "update", "master_data"),
    ("master.employee:delete", "master.employee", "delete", "master_data"),
    ("master.customer:read", "master.customer", "read", "master_data"),
    ("master.customer:create", "master.customer", "create", "master_data"),
    ("master.customer:update", "master.customer", "update", "master_data"),
    ("master.customer:delete", "master.customer", "delete", "master_data"),
    ("master.vendor:read", "master.vendor", "read", "master_data"),
    ("master.vendor:create", "master.vendor", "create", "master_data"),
    ("master.vendor:update", "master.vendor", "update", "master_data"),
    ("master.vendor:delete", "master.vendor", "delete", "master_data"),
    (
        "master.party_registration:read",
        "master.party_registration",
        "read",
        "master_data",
    ),
    (
        "master.party_registration:create",
        "master.party_registration",
        "create",
        "master_data",
    ),
    (
        "master.party_registration:update",
        "master.party_registration",
        "update",
        "master_data",
    ),
    (
        "master.party_registration:delete",
        "master.party_registration",
        "delete",
        "master_data",
    ),
    (
        "master.party_registration:verify_kyc",
        "master.party_registration",
        "verify_kyc",
        "master_data",
    ),
    (
        "master.party_registration:approve",
        "master.party_registration",
        "approve",
        "master_data",
    ),
    ("master.product:read", "master.product", "read", "master_data"),
    ("master.product:create", "master.product", "create", "master_data"),
    ("master.product:update", "master.product", "update", "master_data"),
    ("master.product:delete", "master.product", "delete", "master_data"),
    ("master.product_category:read", "master.product_category", "read", "master_data"),
    ("master.product_category:create", "master.product_category", "create", "master_data"),
    ("master.product_category:update", "master.product_category", "update", "master_data"),
    ("master.product_category:delete", "master.product_category", "delete", "master_data"),
    ("master.uom:read", "master.uom", "read", "master_data"),
    ("master.uom:create", "master.uom", "create", "master_data"),
    ("master.uom:update", "master.uom", "update", "master_data"),
    ("master.uom:delete", "master.uom", "delete", "master_data"),
    ("master.currency:read", "master.currency", "read", "master_data"),
    ("master.currency:create", "master.currency", "create", "master_data"),
    ("master.currency:update", "master.currency", "update", "master_data"),
    ("master.currency:delete", "master.currency", "delete", "master_data"),
    ("master.tax:read", "master.tax", "read", "master_data"),
    ("master.tax:create", "master.tax", "create", "master_data"),
    ("master.tax:update", "master.tax", "update", "master_data"),
    ("master.tax:delete", "master.tax", "delete", "master_data"),
    ("master.asset:read", "master.asset", "read", "master_data"),
    ("master.asset:create", "master.asset", "create", "master_data"),
    ("master.asset:update", "master.asset", "update", "master_data"),
    ("master.asset:delete", "master.asset", "delete", "master_data"),
    ("master.warehouse:read", "master.warehouse", "read", "master_data"),
    ("master.warehouse:create", "master.warehouse", "create", "master_data"),
    ("master.warehouse:update", "master.warehouse", "update", "master_data"),
    ("master.warehouse:delete", "master.warehouse", "delete", "master_data"),
]
