const RAW_LEAD_OEM_OPTIONS = [
  "8x8",
  "ABB",
  "Acer",
  "Acronis",
  "Adobe",
  "Alibaba Cloud",
  "AMD",
  "Amazon Web Services (AWS)",
  "APC",
  "Apple",
  "Arista Networks",
  "Arcserve",
  "ASUS",
  "Atlassian",
  "Avaya",
  "BMC",
  "BeyondTrust",
  "BlackBerry",
  "Broadcom",
  "Brother",
  "Canon",
  "Check Point",
  "Cisco",
  "Citrix",
  "Cohesity",
  "Commvault",
  "CommScope",
  "CrowdStrike",
  "CyberArk",
  "Databricks",
  "Datadog",
  "Dell Technologies",
  "Delta Electronics",
  "DigitalOcean",
  "Docker",
  "Druva",
  "Dynatrace",
  "Eaton",
  "Epson",
  "Ericsson",
  "Extreme Networks",
  "F5",
  "Fortinet",
  "Freshworks",
  "Fujitsu",
  "Gigabyte",
  "Google Cloud",
  "Google",
  "HubSpot",
  "HPE",
  "HPE Aruba Networking",
  "Huawei",
  "Huawei Cloud",
  "IBM",
  "IFS",
  "Intel",
  "Infor",
  "Inspur",
  "Ivanti",
  "Jabra",
  "Juniper Networks",
  "Kaspersky",
  "Kong",
  "Konica Minolta",
  "Kyocera",
  "Legrand",
  "Lenovo",
  "Lexmark",
  "LogicMonitor",
  "Logitech",
  "ManageEngine",
  "MariaDB",
  "Microsoft",
  "Microsoft Azure",
  "Microsoft Dynamics 365",
  "Mitel",
  "MongoDB",
  "MuleSoft",
  "NetApp",
  "NETGEAR",
  "Netskope",
  "New Relic",
  "NVIDIA",
  "Nokia",
  "Nutanix",
  "Okta",
  "OpenAI",
  "OpenText",
  "Oracle",
  "Oracle Cloud",
  "Odoo",
  "Palo Alto Networks",
  "Panduit",
  "Palantir",
  "Ping Identity",
  "Poly",
  "Proofpoint",
  "Pure Storage",
  "PTC",
  "QNAP",
  "Qualys",
  "Red Hat",
  "Ricoh",
  "Riello",
  "RingCentral",
  "Rittal",
  "Rubrik",
  "Ruckus Networks",
  "Salesforce",
  "Samsung",
  "Samsung Networks",
  "SAP",
  "SAS",
  "Schneider Electric",
  "ScienceLogic",
  "SentinelOne",
  "ServiceMax",
  "ServiceNow",
  "Sharp",
  "Siemens",
  "Singtel",
  "SolarWinds",
  "Sophos",
  "Splunk",
  "Supermicro",
  "SUSE",
  "Synology",
  "TIBCO",
  "Tenable",
  "TP-Link",
  "Trend Micro",
  "Ubiquiti",
  "Veritas",
  "Vertiv",
  "Veeam",
  "VMware by Broadcom",
  "Xerox",
  "Yealink",
  "Zscaler",
  "Zoom",
  "Zerto",
  "ZTE",
  "Zoho",
  "ZoomInfo",
  "Snowflake",
  "Anthropic",
  "Cloudflare",
  "SailPoint",
] as const;

export const LEAD_OEM_OPTIONS: readonly string[] = [...new Set(RAW_LEAD_OEM_OPTIONS)];

export const LEAD_OEM_SEPARATOR = ", ";

export function parseLeadOemNames(value: string | null | undefined): string[] {
  if (!value?.trim()) return [];
  return value
    .split(",")
    .map((name) => name.trim())
    .filter(Boolean);
}

export function formatLeadOemNames(names: readonly string[]): string {
  return names.join(LEAD_OEM_SEPARATOR);
}
